name: Micro Documentation
description: This is the Micro documentation web server
# MICRO_ENV: production

repositories:
  partials: {path: views/partials, cache: views}
  content: {path: views/content, cache: views, default: true}
  templates: {path: views/templates, cache: views}

controllers: {path: controllers, cache: memCache}

cache:
  names: [memCache, views]
  class: ca.simplegames.micro.cache.DefaultCache

template_engines:
  - engine:
      name: velocity
      class: ca.simplegames.micro.viewers.velocity.VelocityViewRenderer
      options:
          resource_cache_enabled: true
          resource_cache_interval: 15
          global_macro_library: global_library.vm
      default: true

  - engine:
      name: markdown
      class: ca.simplegames.micro.viewers.markup.MarkupViewRenderer

welcome_file: index.md
mime_types:
  .md: text/html; charset=utf8

LEGACY: true
